export const externalUrls = {
  javascript: "https://www.ecma-international.org/publications-and-standards/standards/ecma-262/",
  typescript: 'https://www.typescriptlang.org/',
  react: 'https://react.dev/',
  'react-query': 'https://react-query-v3.tanstack.com/',
  recoil: 'https://recoiljs.org/',
  'next-js': 'https://nextjs.org/',
  'emotion-js': 'https://emotion.sh/docs/introduction',
  html: 'https://www.w3.org/',
  css: 'https://www.w3.org/TR/CSS/#css',
  jira: 'https://www.atlassian.com/software/jira',
  vsc: 'https://code.visualstudio.com/',
  slack: 'https://slack.com/intl/ko-kr/',
  notion: 'https://www.notion.so/ko-kr',
  git: 'https://github.com/',
} 